Update

diff --git a/o b/o
--- a/o
+++ b/o
@@ -1,1 +1,171 @@
-/usr/bin/open
+#! /bin/sh
+
+while [ $# -gt 0 ] ; do
+    if [ -d "$1" ]; then
+        tmux new-window -c "$PWD"/"$1"
+    elif [ -e "$1" ]; then
+        mime_type=$(file -L -b --mime-type "$1")
+        case $mime_type in
+            inode/x-empty)
+                e "$1"
+                ;;
+            video/*|application/vnd.rn-realmedia)
+                vp "$fp"
+                ;;
+            audio/*)
+                ap "$fp"
+                ;;
+            image/vnd.djvu)
+                dr "$1"
+                ;;
+            image/x-canon-cr2)
+                dcraw -T -w "$1"
+                ;;
+            image/svg+xml|application/x-shockwave-flash)
+                b "$1"
+                ;;
+            image/x-xcf)
+                open -a Gimp "$1"
+                ;;
+            image/*)
+                iv "$1"
+                ;;
+            application/x-lha)
+                lha x "$1"
+                ;;
+            application/postscript)
+                dr "$1"
+                ;;
+            application/pdf)
+                dr "$1"
+                ;;
+            application/zip)
+                unzip -d "${1%.*}" "$1"
+                ;;
+            application/x-tar)
+                tar xvf "$1"
+                ;;
+            application/x-rar)
+                unrar -ad x "$1"
+                ;;
+            application/x-bittorrent)
+                diana_add "$1"
+                ;;
+            application/vnd.ms-opentype|application/x-font-ttf|application/vnd.font-fontforge-sfd)
+                fontforge "$1"
+                ;;
+            text/html)
+                b "$1"
+                ;;
+            text/troff)
+                man -l "$1"
+                ;;
+            *)
+                case "$1" in
+                    *.tar.gz|*.tgz)
+                        tar xvzf "$1"
+                        ;;
+                    *.tar.xz)
+                        tar xvJf "$1"
+                        ;;
+                    *.tar.bz2)
+                        tar xvjf "$1"
+                        ;;
+                    *.bz2)
+                        bunzip2 "$1"
+                        ;;
+                    *.tar)
+                        tar xvf "$1"
+                        ;;
+                    *.gz)
+                        gunzip "$1"
+                        ;;
+                    *.ace)
+                        unace x "$1"
+                        ;;
+                    *.7z)
+                        7z x "$1"
+                        ;;
+                    *.chm)
+                        xchm "$1"
+                        ;;
+                    *.nzb)
+                        nzbget -A "$1"
+                        ;;
+                    *.nfo)
+                        e "$1"
+                        ;;
+                    *.pcf|*.bdf|*.pfb)
+                        fontforge "$1"
+                        ;;
+                    *.svg)
+                        b "$1"
+                        ;;
+                    *.pps|*.PPS|*.ppt|*.PPT)
+                        ppsei "$1"
+                        ;;
+                    *.abw)
+                        abiword "$1"
+                        ;;
+                    *.rtf|*.doc)
+                        catdoc -w -s cp1252 "$1"
+                        ;;
+                    *.xls)
+                        xls2csv -s cp1252 "$1"
+                        ;;
+                    *.xpm)
+                        iv "$1"
+                        ;;
+                    *.mp3|*.m3u|*.ogg)
+                        ap "$fp"
+                        ;;
+                    *.mp4|*.avi|*.mpg|*.mpeg|*.mkv|*.ogv|*.f4v|*.m2ts)
+                        vp "$fp"
+                        ;;
+                    *.webarchive)
+                        tmp_xml=$(mktemp)
+                        tmp_html=$(mktemp)
+                        plutil -i "$1" -o "$tmp_xml"
+                        webarchive_decodemain "$tmp_xml" > "$tmp_html"
+                        b "$tmp_html"
+                        rm "$tmp_xml"
+                        ;;
+                    *.blend)
+                        blender "$1"
+                        ;;
+                    *.emulecollection)
+                        amule-emc "$1"
+                        ;;
+                    *)
+                        mime_encoding=$(file -L -b --mime-encoding "$1")
+                        case $mime_encoding in
+                            *binary)
+                                xxd -l 128 "$1"
+                                ;;
+                            *)
+                                e "$1"
+                                ;;
+                        esac
+                        ;;
+                esac
+                ;;
+        esac
+    else
+        case "$1" in
+            *://*)
+                b "$1"
+                ;;
+            *:*)
+                open "$1"
+                ;;
+            *@*.*)
+                mutt "$1"
+                ;;
+            *)
+                echo "file not found: '$1'" >&2
+                exit 1
+                ;;
+        esac
+    fi
+    shift
+done
